# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
PersonType.create(value: 'Física')
PersonType.create(value: 'Jurídica')

MaritalStatus.create(value: 'Solteiro(a)')
MaritalStatus.create(value: 'Casado(a) ou reside há pelo menos 2 anos com companheiro(a)')
MaritalStatus.create(value: 'Viúvo(a)')
MaritalStatus.create(value: 'Separado(a)/Divorciado(a)')
MaritalStatus.create(value: 'Não Informado')

Gender.create(value: 'Masculino')
Gender.create(value: 'Feminino')

SalaryRange.create(value: 'Sem renda')
SalaryRange.create(value: 'Até 2.500')
SalaryRange.create(value: 'De 2.501 a 5.000')
SalaryRange.create(value: 'De 5.001 a 10.000')
SalaryRange.create(value: 'Acima de 10.000')
SalaryRange.create(value: 'Não desejo informar')

Metier.create(value: 'Cultivo de arroz')
Metier.create(value: 'Cultivo de milho')
Metier.create(value: 'Cultivo de trigo')
Metier.create(value: 'Cultivo de outros cereais para grãos')
Metier.create(value: 'Cultivo de algodão herbáceo')
Metier.create(value: 'Cultivo de cana-de-açúcar')
Metier.create(value: 'Cultivo de fumo')
Metier.create(value: 'Cultivo de soja')
Metier.create(value: 'Cultivo de abacaxi')
Metier.create(value: 'Cultivo de amendoim')
Metier.create(value: 'Cultivo de batata inglesa')
Metier.create(value: 'Cultivo de mandioca')
Metier.create(value: 'Cultivo de feijão')
Metier.create(value: 'Cultivo de juta')
Metier.create(value: 'Cultivo de mamona')
Metier.create(value: 'Cultivo de melão')
Metier.create(value: 'Cultivo de tomate (rasteiro)')
Metier.create(value: 'Cultivo de girassol')
Metier.create(value: 'Cultivo de melancia')
Metier.create(value: 'Produção de sementes certificadas para formação de pasto forrageiras')
Metier.create(value: 'Produção de sementes certificadas de lavouras temporárias exclusive pasto forrageiras')
Metier.create(value: 'Cultivo de outros produtos de lavoura temporária não especificados anteriormente')
Metier.create(value: 'Cultivo de cebola')
Metier.create(value: 'Cultivo de alho')
Metier.create(value: 'Cultivo de morango')
Metier.create(value: 'Cultivo de outros produtos hortícolas')
Metier.create(value: 'Cultivo de flores e plantas ornamentais e produtos de viveiros')
Metier.create(value: 'Cultivo de laranja')
Metier.create(value: 'Cultivo de outros cítricos')
Metier.create(value: 'Cultivo de café')
Metier.create(value: 'Cultivo de cacau')
Metier.create(value: 'Cultivo de uva')
Metier.create(value: 'Cultivo de banana')
Metier.create(value: 'Cultivo de caju')
Metier.create(value: 'Cultivo de coco-da-baía')
Metier.create(value: 'Cultivo de pimenta do reino')
Metier.create(value: 'Cultivo de chá-da-índia')
Metier.create(value: 'Cultivo de maçã')
Metier.create(value: 'Cultivo de mamão')
Metier.create(value: 'Cultivo de manga')
Metier.create(value: 'Cultivo de maracujá')
Metier.create(value: 'Cultivo de erva-mate')
Metier.create(value: 'Cultivo de açaí')
Metier.create(value: 'Cultivo de pêssego')
Metier.create(value: 'Cultivo de seringueira')
Metier.create(value: 'Cultivo de guaraná')
Metier.create(value: 'Cultivo de dendê')
Metier.create(value: 'Cultivo de outras plantas para condimento')
Metier.create(value: 'Cultivo de outros produtos de lavoura permanente não especificados anteriormente')
Metier.create(value: 'Criação de bovinos para corte')
Metier.create(value: 'Criação de bovinos para leite')
Metier.create(value: 'Criação de bubalinos')
Metier.create(value: 'Criação de equinos')
Metier.create(value: 'Criação de outros animais de grande porte')
Metier.create(value: 'Criação de ovinos e produção de lã')
Metier.create(value: 'Criação de suínos')
Metier.create(value: 'Criação de galináceos para corte')
Metier.create(value: 'Criação de pintos de um dia')
Metier.create(value: 'Criação de outras aves')
Metier.create(value: 'Produção de ovos')
Metier.create(value: 'Criação de caprinos')
Metier.create(value: 'Sericicultura')
Metier.create(value: 'Apicultura')
Metier.create(value: 'Ranicultura')
Metier.create(value: 'Criação de escargot')
Metier.create(value: 'Criação de animais domésticos')
Metier.create(value: 'Criação de outros animais')
Metier.create(value: 'Agropecuária')
Metier.create(value: 'Serviço de jardinagem - inclusive plantio de gramado')
Metier.create(value: 'Serviço de pulverização da lavoura')
Metier.create(value: 'Serviço de poda de árvores')
Metier.create(value: 'Serviço de colheita')
Metier.create(value: 'Serviços relacionados ao tratamento de produtos agrícolas')
Metier.create(value: 'Outras atividades de serviços relacionados com a agricultura')
Metier.create(value: 'Serviço de inseminação artificial')
Metier.create(value: 'Serviço de inspeção sanitária')
Metier.create(value: 'Serviço de tosquiamento de ovelhas')
Metier.create(value: 'Serviço de manejo de animais')
Metier.create(value: 'Outras atividades de serviços relacionados com a pecuária - exceto atividades veterinárias')
Metier.create(value: 'Caça')
Metier.create(value: 'Cultivo de eucalipto')
Metier.create(value: 'Cultivo de acácia negra')
Metier.create(value: 'Cultivo de pinus')
Metier.create(value: 'Cultivo de teca')
Metier.create(value: 'Cultivo de outras espécies de madeira')
Metier.create(value: 'Cultivo de mudas em viveiros florestais')
Metier.create(value: 'Extração de madeira')
Metier.create(value: 'Produção de casca de acácia negra')
Metier.create(value: 'Coleta de látex (borracha extrativa)')
Metier.create(value: 'Coleta de castanha-do-pará')
Metier.create(value: 'Coleta de palmito')
Metier.create(value: 'Coleta de outros produtos florestais silvestres')
Metier.create(value: 'Atividades dos serviços relacionados com a silvicultura e a exploração florestal')
Metier.create(value: 'Pesca de peixes')
Metier.create(value: 'Pesca de crustáceos e moluscos')
Metier.create(value: 'Coleta de produtos de origem marinha')
Metier.create(value: 'Atividades de serviços relacionados a pesca')
Metier.create(value: 'Criação de peixes')
Metier.create(value: 'Criação de camarões')
Metier.create(value: 'Criação de ostras e mexilhões')
Metier.create(value: 'Criação de peixes ornamentais')
Metier.create(value: 'Atividades de serviços relacionados a aquicultura')
Metier.create(value: 'Outros cultivos e semicultivos da aquicultura')
Metier.create(value: 'Extração de carvão mineral')
Metier.create(value: 'Beneficiamento de carvão mineral')
Metier.create(value: 'Extração de petróleo e gás natural')
Metier.create(value: 'Extração e beneficiamento de xisto')
Metier.create(value: 'Extração e beneficiamento de areias betuminosas')
Metier.create(value: 'Serviços relacionados com a extração de petróleo - exceto a prospecção realizada por t')
Metier.create(value: 'Extração de minério de ferro')
Metier.create(value: 'Pelotização sinterização e outros beneficiamentos de minério de ferro')
Metier.create(value: 'Extração de minério de alumínio')
Metier.create(value: 'Beneficiamento de minério de alumínio')
Metier.create(value: 'Extração de minério de estanho')
Metier.create(value: 'Beneficiamento de minério de estanho')
Metier.create(value: 'Extração de minério de manganês')
Metier.create(value: 'Beneficiamento de minério de manganês')
Metier.create(value: 'Extração de minérios de metais preciosos')
Metier.create(value: 'Extração de minerais radioativos')
Metier.create(value: 'Extração de nióbio e titânio')
Metier.create(value: 'Extração de tungstênio')
Metier.create(value: 'Extração de níquel')
Metier.create(value: 'Extração de cobre chumbo zinco e de outros minerais metálicos não-ferrosos não compr')
Metier.create(value: 'Beneficiamento de cobre chumbo zinco níquel e de outros minerais metálicos não-ferr')
Metier.create(value: 'Extração de ardósia e beneficiamento associado')
Metier.create(value: 'Extração de granito e beneficiamento associado')
Metier.create(value: 'Extração de mármore e beneficiamento associado')
Metier.create(value: 'Extração de calcário/dolomita e beneficiamento associado')
Metier.create(value: 'Extração de gesso e caulim e beneficiamento associado')
Metier.create(value: 'Extração de areia cascalho ou pedregulho e beneficiamento associado')
Metier.create(value: 'Extração de argila e beneficiamento associado')
Metier.create(value: 'Extração de saibro e beneficiamento associado')
Metier.create(value: 'Extração de basalto e beneficiamento associado')
Metier.create(value: 'Extração e/ou britamento de pedras e de outros materiais para construção não especific')
Metier.create(value: 'Extração de minerais para fabricação de adubos fertilizantes e produtos químicos')
Metier.create(value: 'Extração de sal marinho')
Metier.create(value: 'Extração de sal-gema')
Metier.create(value: 'Refino e outros tratamentos do sal')
Metier.create(value: 'Extração de gemas')
Metier.create(value: 'Extração de grafita')
Metier.create(value: 'Extração de quartzo e cristal de rocha')
Metier.create(value: 'Extração de amianto')
Metier.create(value: 'Extração de outros minerais não-metálicos não especificados anteriormente')
Metier.create(value: 'Frigorífico - Abate de bovinos e preparação de carne e subprodutos')
Metier.create(value: 'Frigorífico - Abate de suínos e preparação de carne e subprodutos')
Metier.create(value: 'Frigorífico - Abate de equinos e preparação de carne e subprodutos')
Metier.create(value: 'Frigoríficos - Abate de ovinos e caprinos e preparação de carne e subprodutos')
Metier.create(value: 'Frigorífico - abate de bubalinos e preparação de carne e subprodutos')
Metier.create(value: 'Matadouro - abate de reses e preparação de carne para terceiros')
Metier.create(value: 'Abate de aves e preparação de produtos de carne')
Metier.create(value: 'Abate de pequenos animais e preparação de produtos de carne')
Metier.create(value: 'Preparação de carne banha e produtos de salsicharia não associadas ao abate')
Metier.create(value: 'Preparação de subprodutos não associado ao abate')
Metier.create(value: 'Preparação e conservação do pescado e fabricação de conservas de peixes crustáceos e')
Metier.create(value: 'Processamento preservação e produção de conservas de frutas')
Metier.create(value: 'Processamento preservação e produção de conservas de legumes e outros vegetais')
Metier.create(value: 'Produção de sucos de frutas e de legumes')
Metier.create(value: 'produção de óleos vegetais em bruto')
Metier.create(value: 'Refino de óleos vegetais')
Metier.create(value: 'Preparação de margarina e outras gorduras vegetais e de óleos de origem animal não com')
Metier.create(value: 'Preparação do leite')
Metier.create(value: 'Fabricação de produtos do laticínios')
Metier.create(value: 'Fabricação de sorvetes')
Metier.create(value: 'Beneficiamento de arroz')
Metier.create(value: 'Fabricação de produtos do arroz')
Metier.create(value: 'Moagem de trigo e fabricação de derivados')
Metier.create(value: 'Produção de farinha de mandioca e derivados')
Metier.create(value: 'Fabricação de fubá farinha e outros derivados de milho - exclusive óleo')
Metier.create(value: 'Fabricação de amidos e féculas de vegetais e fabricação de óleos de milho')
Metier.create(value: 'Fabricação de rações balanceadas para animais')
Metier.create(value: 'Beneficiamento moagem e preparação de outros produtos de origem vegetal')
Metier.create(value: 'Usinas de açúcar')
Metier.create(value: 'Refino e moagem de açúcar de cana')
Metier.create(value: 'Fabricação de açúcar de cereais (dextrose) e de beterraba')
Metier.create(value: 'Fabricação de açúcar de stévia')
Metier.create(value: 'Beneficiamento de café')
Metier.create(value: 'Torrefação e moagem de café')
Metier.create(value: 'Fabricação de café solúvel')
Metier.create(value: 'Fabricação de pães bolos e equivalentes industrializados')
Metier.create(value: 'Fabricação de produtos de padaria confeitaria e pastelaria exclusive industrializados')
Metier.create(value: 'Fabricação de biscoitos e bolachas')
Metier.create(value: 'Produção de derivados do cacau e elaboração de chocolates')
Metier.create(value: 'Produção de balas e semelhantes e de frutas cristalizadas')
Metier.create(value: 'Fabricação de massas alimentícias')
Metier.create(value: 'Preparação de especiarias molhos temperos e condimentos')
Metier.create(value: 'Preparação de produtos dietéticos alimentos para crianças e outros alimentos conserva')
Metier.create(value: 'Fabricação de vinagres')
Metier.create(value: 'Fabricação de pós alimentícios')
Metier.create(value: 'Fabricação de fermentos leveduras e coalhos')
Metier.create(value: 'Fabricação de gelo comum')
Metier.create(value: 'Beneficiamento de chá mate e outras ervas para infusão')
Metier.create(value: 'Fabricação de outros produtos alimentícios')
Metier.create(value: 'Fabricação retificação homogeneização e mistura de aguardente de cana-de-açúcar')
Metier.create(value: 'Fabricação retificação homogeneização e mistura de outras aguardentes e bebidas dest')
Metier.create(value: 'Fabricação de vinho')
Metier.create(value: 'Fabricação de malte inclusive malte uísque')
Metier.create(value: 'Fabricação de cervejas e chopes')
Metier.create(value: 'Engarrafamento e gaseificação de águas minerais')
Metier.create(value: 'Fabricação de refrigerantes')
Metier.create(value: 'Fabricação de refrescos xaropes e pós para refrescos')
Metier.create(value: 'Fabricação de cigarros e cigarrilhas')
Metier.create(value: 'Fabricação de fumo em rolo ou em corda e outros produtos do fumo')
Metier.create(value: 'Fabricação de filtros para cigarros')
Metier.create(value: 'Beneficiamento de algodão')
Metier.create(value: 'Beneficiamento de outras fibras têxteis naturais')
Metier.create(value: 'Fiação de algodão')
Metier.create(value: 'Fiação de outras fibras têxteis naturais')
Metier.create(value: 'Fiação de fibras artificiais ou sintéticas')
Metier.create(value: 'Fabricação de linhas e fios para coser e bordar')
Metier.create(value: 'Tecelagem de algodão')
Metier.create(value: 'Tecelagem de fios de fibras têxteis naturais')
Metier.create(value: 'Tecelagem de fios e filamentos contínuos artificiais ou sintéticos')
Metier.create(value: 'Fabricação de artigos de tecido de uso doméstico incluindo tecelagem')
Metier.create(value: 'Fabricação de outros artefatos têxteis incluindo tecelagem')
Metier.create(value: 'Estamparia e texturização em fios tecidos e artigos têxteis inclusive em confecções')
Metier.create(value: 'Alvejamento tingimento e torção em fios tecidos e artigos têxteis inclusive em conf')
Metier.create(value: 'Outros serviços de acabamento em fios tecidos e artigos têxteis inclusive em confecç')
Metier.create(value: 'Fabricação de artefatos têxteis a partir de tecidos exclusive vestuário')
Metier.create(value: 'Fabricação de artefatos de tapeçaria')
Metier.create(value: 'Fabricação de artefatos de cordoaria')
Metier.create(value: 'Fabricação de tecidos especiais - inclusive artefatos')
Metier.create(value: 'Fabricação de outros artigos têxteis - exclusive vestuário')
Metier.create(value: 'Fabricação de tecidos de malha')
Metier.create(value: 'Fabricação de meias')
Metier.create(value: 'Fabricação de outros artigos do vestuário produzidos em malharias (tricotagens)')
Metier.create(value: 'Confecção de peças interiores do vestuário exclusive sob medida')
Metier.create(value: 'Confecção sob medida de peças interiores do vestuário')
Metier.create(value: 'Confecção de outras peças do vestuário exclusive sob medida')
Metier.create(value: 'Confecção sob medida  de outras peças do vestuário')
Metier.create(value: 'Confecção de roupas profissionais exclusive sob medida')
Metier.create(value: 'Confecção sob medida de roupas profissionais')
Metier.create(value: 'Fabricação de acessórios do vestuário')
Metier.create(value: 'Fabricação de acessórios para segurança industrial e pessoal')
Metier.create(value: 'Curtimento e outras preparações de couro')
Metier.create(value: 'Fabricação de malas bolsas valises e outros artefatos para viagem de qualquer mater')
Metier.create(value: 'Fabricação de outros artefatos de couro')
Metier.create(value: 'Fabricação de calçados de couro')
Metier.create(value: 'Serviço de corte e acabamento de calçados')
Metier.create(value: 'Fabricação de tênis de qualquer material')
Metier.create(value: 'Fabricação de calçados de plástico')
Metier.create(value: 'Fabricação de calçados de outros materiais')
Metier.create(value: 'Serrarias com desdobramento de madeira')
Metier.create(value: 'Serrarias sem desdobramento de madeira')
Metier.create(value: 'Fabricação de madeira laminada e de chapas de madeira compensada prensada ou aglomera')
Metier.create(value: 'Produção de casas de madeira pré-fabricadas')
Metier.create(value: 'Fabricação de esquadrias de madeira veneziana e de peças de madeira para instalações')
Metier.create(value: 'Fabricação de outros artigos de carpintaria')
Metier.create(value: 'Fabricação de artefatos de tanoaria e embalagens de madeira')
Metier.create(value: 'Fabricação de artefatos diversos de madeira palha cortiça e material trançado - excl')
Metier.create(value: 'Fabricação de celulose e outras pastas para a fabricação de papel')
Metier.create(value: 'Fabricação de papel')
Metier.create(value: 'Fabricação de papelão liso cartolina e cartão')
Metier.create(value: 'Fabricação de embalagens de papel')
Metier.create(value: 'Fabricação de embalagens de papelão - inclusive a fabricação de papelão corrugado')
Metier.create(value: 'Fabricação de artefatos de papel papelão cartolina e cartão para escritório')
Metier.create(value: 'Fabricação de fitas e formulários contínuos - impressos ou não')
Metier.create(value: 'Fabricação de fraldas descartáveis e de absorventes higiênicos')
Metier.create(value: 'Fabricação de outros artefatos de pastas papel papelão cartolina e cartão')
Metier.create(value: 'Edição; edição e impressão de jornais')
Metier.create(value: 'Edição; edição e impressão de revistas')
Metier.create(value: 'Edição; edição e impressão de livros')
Metier.create(value: 'Edição de discos fitas e outros materiais gravados')
Metier.create(value: 'Edição; edição e impressão de produtos gráficos')
Metier.create(value: 'Fabricação de artefatos de borracha não especificados anteriormente')
Metier.create(value: 'Impressão de jornais revistas e livros')
Metier.create(value: 'Impressão de material para uso escolar')
Metier.create(value: 'Impressão de material para uso industrial comercial e publicitário')
Metier.create(value: 'Impressão de material de segurança')
Metier.create(value: 'Serviços de encadernação e plastificação')
Metier.create(value: 'Composição de matrizes para impressão gráfica')
Metier.create(value: 'Outros serviços gráficos')
Metier.create(value: 'Reprodução de discos e fitas')
Metier.create(value: 'Reprodução de fitas de vídeos')
Metier.create(value: 'Reprodução de filmes')
Metier.create(value: 'Reprodução de programas de informática em disquetes e fitas')
Metier.create(value: 'Coquerias')
Metier.create(value: 'Refino de petróleo')
Metier.create(value: 'Elaboração de combustíveis nucleares')
Metier.create(value: 'Fabricação de álcool')
Metier.create(value: 'Fabricação de cloro e álcalis')
Metier.create(value: 'Fabricação de intermediários para fertilizantes')
Metier.create(value: 'Fabricação de fertilizantes fosfatados nitrogenados e potássicos')
Metier.create(value: 'Fabricação de gases industriais')
Metier.create(value: 'Fabricação de outros produtos inorgânicos')
Metier.create(value: 'Fabricação de produtos petroquímicos básicos')
Metier.create(value: 'Fabricação de intermediários para resinas e fibras')
Metier.create(value: 'Fabricação de outros produtos químicos orgânicos')
Metier.create(value: 'Fabricação de resinas termoplásticas')
Metier.create(value: 'Fabricação de resinas termofixas')
Metier.create(value: 'Fabricação de elastômeros')
Metier.create(value: 'Fabricação de fibras fios cabos e filamentos contínuos artificiais')
Metier.create(value: 'Fabricação de fibras fios cabos e filamentos contínuos sintéticos')
Metier.create(value: 'Fabricação de produtos farmoquímicos')
Metier.create(value: 'Fabricação de medicamentos alopáticos para uso humano')
Metier.create(value: 'Fabricação de medicamentos homeopáticos para uso humano')
Metier.create(value: 'Fabricação de medicamentos para uso veterinário')
Metier.create(value: 'Fabricação de materiais para usos médicos hospitalares e odontológicos')
Metier.create(value: 'Fabricação de inseticidas')
Metier.create(value: 'Fabricação de fungicidas')
Metier.create(value: 'Fabricação de herbicidas')
Metier.create(value: 'Fabricação de outros defensivos agrícolas')
Metier.create(value: 'Fabricação de sabões sabonetes e detergentes sintéticos')
Metier.create(value: 'Fabricação de produtos de limpeza e polimento')
Metier.create(value: 'Fabricação de artigos de perfumaria e cosméticos')
Metier.create(value: 'Fabricação de tintas vernizes esmaltes e lacas')
Metier.create(value: 'Fabricação de tintas de impressão')
Metier.create(value: 'Fabricação de impermeabilizantes solventes e produtos afins')
Metier.create(value: 'Fabricação de adesivos e selantes')
Metier.create(value: 'Fabricação de pólvoras explosivos e detonantes')
Metier.create(value: 'Fabricação de artigos pirotécnicos')
Metier.create(value: 'Fabricação de catalisadores')
Metier.create(value: 'Fabricação de aditivos de uso industrial')
Metier.create(value: 'Fabricação de chapas filmes papéis e outros materiais produtos químicos parra fotogr')
Metier.create(value: 'Fabricação de discos e fitas virgens')
Metier.create(value: 'Fabricação de outros produtos químicos não especificados ou não classificados')
Metier.create(value: 'Fabricação de pneumáticos e de câmaras de ar')
Metier.create(value: 'Recondicionamento de pneumáticos')
Metier.create(value: 'Fabricação de artefatos diversos de borracha')
Metier.create(value: 'Fabricação de laminados planos e tubulares de plástico')
Metier.create(value: 'Fabricação de embalagem de plástico')
Metier.create(value: 'Fabricação de artefatos de material plástico para uso pessoal e doméstico reforçados')
Metier.create(value: 'Fabricação de artefatos de material plástico para usos industriais - exclusive na indú')
Metier.create(value: 'Fabricação de artefatos de material plástico para uso na construção civil')
Metier.create(value: 'Fabricação de artefatos de plástico para outros usos')
Metier.create(value: 'Fabricação de vidro plano e de segurança')
Metier.create(value: 'Fabricação de embalagens de vidro')
Metier.create(value: 'Fabricação de artigos de vidro')
Metier.create(value: 'Fabricação de cimento')
Metier.create(value: 'Fabricação de estruturas pré-moldadas de concreto armado em série ou sob encomenda')
Metier.create(value: 'Fabricação de artefatos de cimento para uso na construção civil')
Metier.create(value: 'Fabricação de artefatos de fibrocimento para uso na construção civil')
Metier.create(value: 'Fabricação de casas pré-moldadas de concreto')
Metier.create(value: 'Preparação de massa de concreto e argamassa para construção')
Metier.create(value: 'Fabricação de outros artefatos ou produtos de concreto cimento fibrocimento gesso e')
Metier.create(value: 'Fabricação de artefatos de cerâmica ou barro cozido para uso na construção civil - exc')
Metier.create(value: 'Fabricação de azulejos e pisos')
Metier.create(value: 'Fabricação de produtos cerâmicos refratários')
Metier.create(value: 'Fabricação de material sanitário de cerâmica')
Metier.create(value: 'Fabricação de outros produtos cerâmicos não-refratários para usos diversos')
Metier.create(value: 'Britamento de pedras (não associado . extração)')
Metier.create(value: 'Aparelhamento de pedras para construção (não associado . extração)')
Metier.create(value: 'Aparelhamento de placas e execução de trabalhos em mármore granito ardósia e outras')
Metier.create(value: 'Fabricação de cal virgem cal hidratada e gesso')
Metier.create(value: 'Fabricação de outros produtos de minerais não metálicos')
Metier.create(value: 'Produção de laminados planos de aço comum revestidos ou não')
Metier.create(value: 'Produção de laminados planos de aços especiais')
Metier.create(value: 'Produção de tubos e canos sem costura')
Metier.create(value: 'Produção de outros laminados não-planos de aço')
Metier.create(value: 'Produção de gusa')
Metier.create(value: 'Produção de ferro aço e ferro ligas em formas primárias e semiacabados')
Metier.create(value: 'Produção de arames de aço')
Metier.create(value: 'Produção de relaminados trefilados e retrefilados de aço e de perfis estampados - ex')
Metier.create(value: 'Fabricação de tubos de aço com costura')
Metier.create(value: 'Fabricação de outros tubos de ferro e aço')
Metier.create(value: 'Metalurgia do alumínio e suas ligas')
Metier.create(value: 'Produção de laminados de alumínio')
Metier.create(value: 'Metalurgia dos metais preciosos')
Metier.create(value: 'Metalurgia do zinco')
Metier.create(value: 'Produção de laminados de zinco')
Metier.create(value: 'Produção de soldas e anodos para galvanoplastia')
Metier.create(value: 'Metalurgia de outros metais não-ferrosos')
Metier.create(value: 'Produção de peças fundidas de ferro e aço')
Metier.create(value: 'Produção de peças fundidas de metais não-ferrosos e suas ligas')
Metier.create(value: 'Fabricação de estruturas metálicas para edifícios pontes torres de transmissão and')
Metier.create(value: 'Fabricação de esquadrias de metal')
Metier.create(value: 'Fabricação de obras de caldeiraria pesada')
Metier.create(value: 'Fabricação de tanques reservatórios metálicos e caldeiras para aquecimento central')
Metier.create(value: 'Manutenção e reparação de tanques reservatórios metálicos e caldeiras para aquecimento')
Metier.create(value: 'Fabricação de caldeiras geradoras de vapor - exclusive para aquecimento central e para')
Metier.create(value: 'Manutenção e reparação de caldeiras geradoras de vapor - exclusive para aquecimento ce')
Metier.create(value: 'Produção de forjados de aço')
Metier.create(value: 'Produção de forjados de metais não-ferrosos e suas ligas')
Metier.create(value: 'Produção de artefatos estampados de metal')
Metier.create(value: 'Metalurgia do pó')
Metier.create(value: 'Têmpera cementação e tratamento térmico do aço serviços de usinagem galvanotécnica')
Metier.create(value: 'Fabricação de artigos de cutelaria')
Metier.create(value: 'Fabricação de artigos de serralheria')
Metier.create(value: 'Fabricação de ferramentas manuais')
Metier.create(value: 'Fabricação de embalagens metálicas')
Metier.create(value: 'Fabricação de produtos padronizados trefilados de ferro aço e de metais não-ferrosos')
Metier.create(value: 'Fabricação de outros produtos de trefilados de ferro aço e de metais não-ferrosos')
Metier.create(value: 'Fabricação de artigos de funilaria e de artigos de metal para usos doméstico e pessoal')
Metier.create(value: 'Fabricação de outros produtos elaborados de metal')
Metier.create(value: 'Fabricação de motores estacionários de combustão interna turbinas e outras máquinas')
Metier.create(value: 'Instalação reparação e manutenção de máquinas motrizes não-elétricas')
Metier.create(value: 'Fabricação de bombas e carneiros hidráulicos inclusive peças')
Metier.create(value: 'Reparação e manutenção de bombas e carneiros hidráulicos')
Metier.create(value: 'Fabricação de válvulas torneiras e registros inclusive peças')
Metier.create(value: 'Reparação e manutenção de válvulas industriais')
Metier.create(value: 'Fabricação de compressores inclusive peças')
Metier.create(value: 'Reparação e manutenção de compressores')
Metier.create(value: 'Fabricação de equipamentos de transmissão para fins industriais - inclusive rolamento')
Metier.create(value: 'Reparação e manutenção de equipamentos de transmissão para fins industriais')
Metier.create(value: 'Especificação incompleta')
Metier.create(value: 'Fabricação de fornos industriais aparelhos e equipamentos não-elétricos para instalaç')
Metier.create(value: 'Instalação reparação e manutenção de fornos industriais aparelhos e equipamentos não')
Metier.create(value: 'Fabricação de estufas elétricas para fins industriais - inclusive peças')
Metier.create(value: 'Instalação reparação e manutenção de estufas elétricas para fins industriais')
Metier.create(value: 'Fabricação de máquinas equipamentos para transporte e elevação de cargas e pessoas -')
Metier.create(value: 'Fabricação de máquinas e aparelhos de refrigeração e ventilação de uso industrial - in')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e aparelhos de refrigeração e ventilaçã')
Metier.create(value: 'Fabricação de equipamentos de ar condicionado')
Metier.create(value: 'Fabricação de outras máquinas e equipamentos de uso geral - inclusive peças')
Metier.create(value: 'Instalação reparação e manutenção de outras máquinas e equipamentos de uso geral')
Metier.create(value: 'Fabricação de máquinas e equipamentos para agricultura avicultura e obtenção de produ')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e equipamentos para agricultura avicul')
Metier.create(value: 'Fabricação de tratores agrícolas - inclusive peças')
Metier.create(value: 'Reparação e manutenção de tratores agrícolas')
Metier.create(value: 'Fabricação de máquinas-ferramenta - inclusive peças')
Metier.create(value: 'Instalação reparação e manutenção de máquinas-ferramenta')
Metier.create(value: 'Fabricação de máquinas e equipamentos para a indústria de prospecção e extração de pet')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e equipamentos para prospecção e extraç')
Metier.create(value: 'Fabricação de outras máquinas e equipamentos para extração de minérios e indústria da')
Metier.create(value: 'Instalação reparação e manutenção de outras máquinas e equipamentos para extração de')
Metier.create(value: 'Fabricação de tratores de esteira e tratores de uso na construção e mineração - inclusi')
Metier.create(value: 'Reparação e manutenção de tratores de esteira e tratores de uso na construção e minera')
Metier.create(value: 'Fabricação de máquinas e equipamentos de terraplenagem e pavimentação')
Metier.create(value: 'Reparação e manutenção de máquinas e equipamentos de terraplenagem e pavimentação')
Metier.create(value: 'Fabricação de máquinas para a indústria metalúrgica inclusive peças - exclusive máqui')
Metier.create(value: 'Instalação reparação e manutenção de máquinas para indústria metalúrgica')
Metier.create(value: 'Fabricação de máquinas e equipamentos para industrias alimentar de bebida e fumo - in')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e equipamentos para as industrias alime')
Metier.create(value: 'Fabricação de máquinas e equipamentos para a indústria têxtil - inclusive peças')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e equipamentos para a indústria têxtil')
Metier.create(value: 'Fabricação de máquinas e equipamentos para as indústrias do vestuário e de couro e cal')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e equipamentos do vestuário')
Metier.create(value: 'Fabricação de máquinas e aparelhos para a indústria de celulose papel e papelão - inc')
Metier.create(value: 'Instalação reparação e manutenção de máquinas e aparelhos para a indústria de celulos')
Metier.create(value: 'Fabricação de outras máquinas e equipamentos de uso específico - inclusive peças')
Metier.create(value: 'Instalação reparação e manutenção de outras máquinas e equipamentos de uso específico')
Metier.create(value: 'Fabricação de armas de fogo e munições')
Metier.create(value: 'Fabricação de equipamento bélico pesado')
Metier.create(value: 'Fabricação de fogões refrigeradores e máquinas de lavar e secar para uso doméstico -')
Metier.create(value: 'Fabricação de outros aparelhos eletrodomésticos - inclusive peças')
Metier.create(value: 'Fabricação de máquinas de escrever e calcular copiadoras e outros equipamentos não-el')
Metier.create(value: 'Fabricação de máquinas de escrever e calcular copiadoras e outros equipamentos eletrô')
Metier.create(value: 'Fabricação de computadores')
Metier.create(value: 'Fabricação de equipamentos periféricos para máquinas eletrônicas para tratamento de in')
Metier.create(value: 'Fabricação de geradores de corrente contínua ou alternada inclusive peças')
Metier.create(value: 'Instalação reparação e manutenção de geradores de corrente continua ou alternada')
Metier.create(value: 'Fabricação de transformadores indutores conversores sincronizadores e semelhantes')
Metier.create(value: 'Instalação reparação e manutenção de transformadores indutores conversores sincron')
Metier.create(value: 'Fabricação de motores elétricos inclusive peças')
Metier.create(value: 'Recuperação de motores elétricos')
Metier.create(value: 'Fabricação de subestações quadros de comando reguladores de voltagem e outros aparel')
Metier.create(value: 'Fabricação de material elétrico para instalações em circuito de consumo')
Metier.create(value: 'Fabricação de fios cabos e condutores elétricos isolados')
Metier.create(value: 'Fabricação de pilhas baterias e acumuladores elétricos - exclusive para veículos')
Metier.create(value: 'Fabricação de baterias e acumuladores para veículos')
Metier.create(value: 'Recondicionamento de baterias e acumuladores para veículos')
Metier.create(value: 'Fabricação de lâmpadas')
Metier.create(value: 'Fabricação de luminárias e equipamentos de iluminação - exclusive para veículos')
Metier.create(value: 'Fabricação de material elétrico para veículos - exclusive baterias')
Metier.create(value: 'Fabricação de eletrodos contatos e outros artigos de carvão e grafita para uso elétri')
Metier.create(value: 'Fabricação de aparelhos e equipamentos para sinalização e alarme')
Metier.create(value: 'Fabricação de outros aparelhos ou equipamentos elétricos')
Metier.create(value: 'Fabricação de material eletrônico básico')
Metier.create(value: 'Fabricação de equipamentos transmissores de rádio e televisão e de equipamentos para e')
Metier.create(value: 'Manutenção de equipamentos transmissores de rádio e televisão e de equipamentos para e')
Metier.create(value: 'Fabricação de aparelhos telefônicos sistemas de intercomunicação e semelhantes inclu')
Metier.create(value: 'Manutenção e reparação de sistemas de intercomunicação e semelhantes')
Metier.create(value: 'Fabricação de aparelhos receptores de rádio e televisão e de reprodução gravação ou a')
Metier.create(value: 'Fabricação de aparelhos equipamentos e mobiliários para instalações hospitalares em')
Metier.create(value: 'Fabricação de instrumentos e utensílios para usos médicos cirúrgicos odontológicos e')
Metier.create(value: 'Fabricação de aparelhos e utensílios para correção de defeitos físicos e aparelhos ort')
Metier.create(value: 'Manutenção e reparação de aparelhos e utensílios para usos médico-hospitalares odonto')
Metier.create(value: 'Serviços de prótese dentária')
Metier.create(value: 'Fabricação de aparelhos e instrumentos de medida teste e controle - exclusive equipam')
Metier.create(value: 'Manutenção e reparação de aparelhos e instrumentos de medida teste e controle - exclu')
Metier.create(value: 'Fabricação de máquinas aparelhos e equipamentos de sistemas eletrônicos dedicados a a')
Metier.create(value: 'Manutenção e instalação de máquinas aparelhos e equipamentos de sistemas eletrônicos')
Metier.create(value: 'Fabricação de aparelhos fotográficos e cinematográficos peças e acessórios')
Metier.create(value: 'Fabricação de instrumentos ópticos peças e acessórios')
Metier.create(value: 'Fabricação de material óptico')
Metier.create(value: 'Serviços de laboratórios ópticos')
Metier.create(value: 'Manutenção e reparação de aparelhos de instrumentos ópticos e cinematográficos')
Metier.create(value: 'Fabricação de cronômetros e relógios')
Metier.create(value: 'Fabricação de automóveis caminhonetas e utilitários')
Metier.create(value: 'Fabricação de chassis com motor para automóveis caminhonetas e utilitários')
Metier.create(value: 'Fabricação de motores para automóveis caminhonetas e utilitários')
Metier.create(value: 'Fabricação de caminhões e ônibus')
Metier.create(value: 'Fabricação de motores para caminhões e ônibus')
Metier.create(value: 'Fabricação de cabines carrocerias e reboques para caminhão')
Metier.create(value: 'Fabricação de carrocerias para ônibus')
Metier.create(value: 'Fabricação de cabines carrocerias e reboques para outros veículos')
Metier.create(value: 'Fabricação de peças e acessórios para o sistema motor')
Metier.create(value: 'Fabricação de peças e acessórios para os sistemas de marcha e transmissão')
Metier.create(value: 'Fabricação de peças e acessórios para o sistema de freios')
Metier.create(value: 'Fabricação de peças e acessórios para o sistema de direção e suspensão')
Metier.create(value: 'Fabricação de peças e acessórios de metal para veículos automotores não classificados')
Metier.create(value: 'Recondicionamento ou recuperação de motores para veículos automotores')
Metier.create(value: 'Construção e reparação de embarcações de grande porte')
Metier.create(value: 'Construção de embarcações para uso comercial e para usos especiais exclusive de gran')
Metier.create(value: 'Reparação de embarcações para uso comercial e para usos especiais exclusive de grande')
Metier.create(value: 'Construção de embarcações para esporte e lazer')
Metier.create(value: 'Reparação de embarcações para esporte e lazer')
Metier.create(value: 'Construção e montagem de locomotivas vagões e outros materiais rodantes')
Metier.create(value: 'Fabricação de peças e acessórios para veículos ferroviários')
Metier.create(value: 'Reparação de veículos ferroviários')
Metier.create(value: 'Construção e montagem de aeronaves')
Metier.create(value: 'Reparação de aeronaves')
Metier.create(value: 'Fabricação de motocicletas - inclusive peças')
Metier.create(value: 'Fabricação de bicicletas e triciclos não-motorizados - inclusive peças')
Metier.create(value: 'Fabricação de outros equipamentos de transporte')
Metier.create(value: 'Fabricação de móveis com predominância de madeira')
Metier.create(value: 'Serviços de montagem de móveis de madeira para consumidor final')
Metier.create(value: 'Fabricação de móveis com predominância de metal')
Metier.create(value: 'Serviços de montagem de móveis de metal para consumidor final')
Metier.create(value: 'Fabricação de móveis de outros materiais')
Metier.create(value: 'Serviços de montagem de móveis de materiais diversos (exclusive madeira e metal) para')
Metier.create(value: 'Fabricação de bancos e estofados para veículos')
Metier.create(value: 'Fabricação de colchões')
Metier.create(value: 'Lapidação de gemas')
Metier.create(value: 'A fabricação de artefatos de joalheria e ourivesaria')
Metier.create(value: 'A cunhagem de moedas e medalhas')
Metier.create(value: 'Fabricação de instrumentos musicais peças e acessórios')
Metier.create(value: 'Fabricação de artefatos para caça pesca e esporte')
Metier.create(value: 'Fabricação de mesas de bilhar de snooker e acessórios não associada . locação')
Metier.create(value: 'Fabricação de mesas de bilhar de snooker e acessórios associadas . locação')
Metier.create(value: 'Fabricação de brinquedos e de outros jogos recreativos')
Metier.create(value: 'Fabricação de canetas lápis fitas impressoras para máquinas e outros artigos para es')
Metier.create(value: 'Fabricação de aviamentos para costura')
Metier.create(value: 'Fabricação de escovas pincéis e vassouras')
Metier.create(value: 'Decoração lapidação gravação espelhação bisotagem vitrificação e outros trabalhos')
Metier.create(value: 'Fabricação de fósforos de segurança')
Metier.create(value: 'Fabricação de produtos diversos')
Metier.create(value: 'Reciclagem de sucatas de alumínio')
Metier.create(value: 'reciclagem de outras sucatas metálicas')
Metier.create(value: 'Reciclagem de sucatas não-metálicas')
Metier.create(value: 'Produção de energia elétrica (inclusive produção integrada)')
Metier.create(value: 'Transmissão de energia elétrica')
Metier.create(value: 'Serviço de medição de consumo de energia elétrica')
Metier.create(value: 'Comércio atacadista de energia elétrica')
Metier.create(value: 'Distribuição de energia elétrica')
Metier.create(value: 'Produção e distribuição de gás através de tubulações')
Metier.create(value: 'Distribuição de combustíveis gasosos de qualquer tipo por sistema de tubulação')
Metier.create(value: 'Serviços de medição de consumo de gás')
Metier.create(value: 'Produção e distribuição de vapor e água quente')
Metier.create(value: 'Captação tratamento e distribuição de água canalizada')
Metier.create(value: 'Serviço de medição de consumo de água')
Metier.create(value: 'Demolição de edifícios e outras estruturas')
Metier.create(value: 'Preparação de terrenos')
Metier.create(value: 'Perfurações e execução de fundações destinadas . construção civil')
Metier.create(value: 'Sondagens destinadas . construção civil')
Metier.create(value: 'Terraplenagem e outras movimentações de terra')
Metier.create(value: 'Edificações (residenciais industriais comerciais e de serviços)')
Metier.create(value: 'Obras viárias (rodovias vias férreas e aeroportos)')
Metier.create(value: 'Pintura para sinalização em pistas rodoviárias e aeroportos')
Metier.create(value: 'Grandes estruturas e obras de arte')
Metier.create(value: 'Obras de urbanização e paisagismo')
Metier.create(value: 'Montagem de estruturas metálicas exclusive andaimes')
Metier.create(value: 'Montagens de andaimes')
Metier.create(value: 'Obras marítimas e fluviais')
Metier.create(value: 'Obras de irrigação')
Metier.create(value: 'Construção de redes de água e esgoto')
Metier.create(value: 'Construção de redes de transportes por dutos')
Metier.create(value: 'Perfuração e construção de poços de águas')
Metier.create(value: 'Outras obras de engenharia civil')
Metier.create(value: 'Construção de barragens e represas para geração de energia elétrica')
Metier.create(value: 'Construção de estações e redes de distribuição de energia elétrica')
Metier.create(value: 'Manutenção de redes de distribuição de energia elétrica')
Metier.create(value: 'Construção de estações e redes de telefonia e comunicações')
Metier.create(value: 'manutenção de estações e redes de telefonia e comunicações')
Metier.create(value: 'Construção de obras de prevenção e recuperação do meio ambiente')
Metier.create(value: 'Instalação e manutenção elétrica em edificações inclusive elevadores escadas esteir')
Metier.create(value: 'Instalação e manutenção de sistemas centrais de ar condicionado de ventilação e refri')
Metier.create(value: 'Instalações hidráulicas sanitárias e de gás')
Metier.create(value: 'Instalações de sistema de prevenção contra incêndio')
Metier.create(value: 'Montagem e instalação de sistemas e equipamentos de iluminação e sinalização em vias p')
Metier.create(value: 'Instalação de equipamentos para orientação a navegação marítima fluvial e lacustre')
Metier.create(value: 'Tratamentos acústico e térmico')
Metier.create(value: 'Instalação de anúncios')
Metier.create(value: 'Outras obras de instalações')
Metier.create(value: 'Obras de alvenaria e reboco')
Metier.create(value: 'Obras de acabamento em gesso e estuque')
Metier.create(value: 'Impermeabilização em obras de engenharia civil')
Metier.create(value: 'Serviços de pintura em edificações em geral')
Metier.create(value: 'Instalação de portas janelas tetos divisórias e armários embutidos de qualquer mate')
Metier.create(value: 'Serviços de revestimentos e aplicação de resinas em interiores e exteriores')
Metier.create(value: 'Outras obras de acabamento da construção')
Metier.create(value: 'Aluguel de máquinas e equipamentos de construção e demolição com operários')
Metier.create(value: 'Comércio por atacado automóveis camionetas e utilitários novos e usados')
Metier.create(value: 'Comércio a varejo de automóveis camionetas e utilitários novos')
Metier.create(value: 'Comércio por atacado de caminhões novos e usados')
Metier.create(value: 'Comércio por atacados de reboques e semirreboques novos e usados')
Metier.create(value: 'Comércio por atacado de ônibus e micro-ônibus novos e usados')
Metier.create(value: 'Comércio a varejo de automóveis camionetas e utilitários usados')
Metier.create(value: 'Representantes comerciais e agentes do comércio de veículos automotores')
Metier.create(value: 'Serviços de manutenção e reparação de automóveis')
Metier.create(value: 'Serviços de manutenção e reparação de caminhões ônibus e outros veículos')
Metier.create(value: 'Serviços de lavagem lubrificação e polimento de veículos')
Metier.create(value: 'Serviços de borracheiros e gomaria')
Metier.create(value: 'Serviços de manutenção e reparação de ar condicionado para veículos automotores')
Metier.create(value: 'Serviços de reboque de veículos')
Metier.create(value: 'Comércio por atacado de peças e acessórios novos para veículos automotores')
Metier.create(value: 'Comércio por atacado de pneumáticos e câmaras de ar')
Metier.create(value: 'Comércio a varejo de peças e acessórios novos para veículos automotores')
Metier.create(value: 'Comércio a varejo de pneumáticos e câmaras de ar')
Metier.create(value: 'representantes comerciais e agentes do comércio de peças me acessórios novos e usados')
Metier.create(value: 'Comércio a varejo de peças e acessórios usados para veículos automotores')
Metier.create(value: 'Representantes comerciais e agentes do comércio de peças e acessórios para motocicleta')
Metier.create(value: 'Comércio por atacado de peças e acessórios para motocicletas e motonetas')
Metier.create(value: 'Comércio a varejo de motocicletas e motonetas')
Metier.create(value: 'Comércio a varejo de peças e acessórios para motocicletas e motonetas')
Metier.create(value: 'Intermediários do comércio de peças e acessórios para motocicletas e motonetas')
Metier.create(value: 'Manutenção e reparação de motocicletas e motonetas')
Metier.create(value: 'Comércio a varejo de combustíveis e lubrificantes para veículos automotores')
Metier.create(value: 'Representantes comerciais e agentes do comércio de matérias primas agrícolas animais')
Metier.create(value: 'Representantes comerciais e agentes do comércio de combustíveis minerais metais e pr')
Metier.create(value: 'Representantes comerciais e agentes do comércio de madeira material de construção e f')
Metier.create(value: 'Representantes comerciais e agentes do comércio de máquinas equipamentos industriais')
Metier.create(value: 'Representantes comerciais e agentes do comércio de móveis e artigos de uso doméstico')
Metier.create(value: 'Representantes comerciais e agentes do comércio de têxteis vestuário calçados e arti')
Metier.create(value: 'Representantes comerciais e agentes do comércio de produtos alimentícios bebidas e fu')
Metier.create(value: 'Representantes comerciais e agentes do comércio especializado em produtos não especif')
Metier.create(value: 'Representantes comerciais e agentes do comércio de mercadorias em geral (não-especiali')
Metier.create(value: 'Comércio atacadista de produtos alimentícios industrializados para animais exclusive')
Metier.create(value: 'Comércio atacadista de algodão')
Metier.create(value: 'Comércio atacadista de café em grão')
Metier.create(value: 'Comércio atacadista de soja')
Metier.create(value: 'Comércio atacadista de fumo em folha não beneficiado')
Metier.create(value: 'Comércio atacadista de cacau em baga')
Metier.create(value: 'Comércio atacadista de sementes flores plantas e gramas')
Metier.create(value: 'Comércio atacadista de sisal')
Metier.create(value: 'Comércio atacadista de produtos agrícolas in natura com atividade de acondicionamento')
Metier.create(value: 'Comércio atacadista de outros cereais in natura  leguminosas e matérias primas agrí')
Metier.create(value: 'Comércio atacadista de bovinos')
Metier.create(value: 'Comércio atacadista de equinos')
Metier.create(value: 'Comércio atacadista de ovinos')
Metier.create(value: 'Comércio atacadista de suínos')
Metier.create(value: 'Comércio atacadista de outros animais vivos')
Metier.create(value: 'Comércio atacadista de couros peles chifres ossos cascos crinas lã pelos e cerd')
Metier.create(value: 'Comércio atacadista de leite e produtos do leite')
Metier.create(value: 'Comércio atacadista de cereais beneficiados')
Metier.create(value: 'Comércio atacadista de farinhas amidos e féculas')
Metier.create(value: 'Comércio atacadista de cereais beneficiados farinhas amidos e féculas com ativida')
Metier.create(value: 'Comércio atacadista de frutas verduras raízes tubérculos hortaliças e legumes fres')
Metier.create(value: 'Comércio atacadista de aves vivas e ovos')
Metier.create(value: 'Comércio atacadista de coelhos e outros pequenos animais vivos para alimentação')
Metier.create(value: 'Comércio atacadista de carnes e produtos de carne')
Metier.create(value: 'Comércio atacadista de pescados e frutos do mar')
Metier.create(value: 'Comércio atacadista de água mineral')
Metier.create(value: 'Comércio atacadista de cerveja chope e refrigerante')
Metier.create(value: 'Comércio atacadista de bebidas com atividade de acondicionamento associada')
Metier.create(value: 'Comércio atacadista de outras bebidas em geral')
Metier.create(value: 'Comércio atacadista de fumo beneficiado')
Metier.create(value: 'Comércio atacadista de cigarros cigarrilhas e charutos')
Metier.create(value: 'Comércio atacadista de café torrado moído e solúvel')
Metier.create(value: 'Comércio atacadista de açúcar')
Metier.create(value: 'Comércio atacadista de óleos e gorduras')
Metier.create(value: 'Comércio atacadista de pães bolos biscoitos e similares')
Metier.create(value: 'Comércio atacadista de massas alimentícias em geral')
Metier.create(value: 'Comércio atacadista de sorvetes')
Metier.create(value: 'Comércio atacadista de produtos alimentícios para animais domésticos')
Metier.create(value: 'Comércio atacadista de chocolates confeitos balas bombons e semelhantes')
Metier.create(value: 'Comér4cio atacadista de outros produtos alimentícios não especificados anteriormente')
Metier.create(value: 'Comércio atacadista de outros produtos alimentícios')
Metier.create(value: 'Comércio atacadista de fios e fibras têxteis')
Metier.create(value: 'Comércio atacadista de tecidos')
Metier.create(value: 'Comércio atacadista de artigos de cama mesa e banho')
Metier.create(value: 'Comércio atacadista de artigos de armarinho')
Metier.create(value: 'Comércio atacadista de artigos do vestuário e complementos exclusive profissionais e')
Metier.create(value: 'Comércio atacadista de roupas e acessórios para uso profissional e de segurança do tra')
Metier.create(value: 'Comércio atacadista de bolsas malas e artigos de viagem')
Metier.create(value: 'Comércio atacadista de calçados')
Metier.create(value: 'Comércio atacadista de máquinas aparelhos e equipamentos elétricos de uso pessoal e d')
Metier.create(value: 'Comércio atacadista de aparelhos eletrônicos de uso pessoal e doméstico')
Metier.create(value: 'Comércio atacadista de produtos farmacêuticos de uso humano')
Metier.create(value: 'Comércio atacadista de produtos farmacêuticos de uso veterinário')
Metier.create(value: 'Comércio atacadista de instrumentos e materiais médico-cirúrgico-hospitalares')
Metier.create(value: 'Comércio atacadista de próteses e artigos de ortopedia')
Metier.create(value: 'Comércio atacadista de produtos odontológicos')
Metier.create(value: 'Comércio atacadista de cosméticos e produtos de perfumaria')
Metier.create(value: 'Comércio atacadista de produtos de higiene pessoal')
Metier.create(value: 'Comércio atacadista de artigos de escritório e de papelaria')
Metier.create(value: 'Comércio atacadista de livros jornais e outras publicações')
Metier.create(value: 'Comércio atacadista de produtos de higiene limpeza e conservação domiciliar')
Metier.create(value: 'Comércio atacadista de bicicletas triciclos e outros veículos  recreativos')
Metier.create(value: 'Comércio atacadista de móveis')
Metier.create(value: 'Comércio atacadista de artigos de tapeçaria colchoaria persianas e cortinas')
Metier.create(value: 'Comércio atacadista de lustres luminárias e abajures')
Metier.create(value: 'Comércio atacadista de filmes fitas e discos')
Metier.create(value: 'Comercio atacadista de produtos de higiene  limpeza e conservação domiciliar com at')
Metier.create(value: 'Comércio atacadista de outros artigos de uso pessoal e doméstico')
Metier.create(value: 'Comércio atacadista de álcool carburante gasolina e demais derivados  - exceto trans')
Metier.create(value: 'Comércio atacadista de combustíveis realizado por transportador retalhista (TRR)')
Metier.create(value: 'Comércio atacadista de gás liquefeito de petróleo (GLP)')
Metier.create(value: 'Comércio atacadista de combustíveis de origem vegetal - exceto álcool carburante')
Metier.create(value: 'Comércio atacadista de combustíveis de origem mineral em bruto')
Metier.create(value: 'Comércio atacadista de lubrificantes')
Metier.create(value: 'Comércio atacadista de produtos extrativos de origem mineral')
Metier.create(value: 'Comércio atacadista de madeira em bruto e produtos derivados')
Metier.create(value: 'Comércio atacadista de cimento')
Metier.create(value: 'Comércio atacadista de ferragens e ferramentas')
Metier.create(value: 'Comércio atacadista de tintas vernizes solventes e similares')
Metier.create(value: 'Comércio atacadista de material elétrico para construção')
Metier.create(value: 'Comércio atacadista de mármores e granitos')
Metier.create(value: 'Comércio atacadista de vidros espelhos vitrais e molduras')
Metier.create(value: 'Comércio atacadista de outros materiais para construção')
Metier.create(value: 'Comércio atacadista de defensivos agrícolas adubos fertilizantes e corretivos do sol')
Metier.create(value: 'Comércio atacadista de resinas e elastrômeros')
Metier.create(value: 'Comércio atacadista de outros produtos químicos')
Metier.create(value: 'Comércio atacadista de resíduos e sucatas metálicas')
Metier.create(value: 'Comércio atacadista de resíduos e sucatas não metálicos - exclusive de papel e papelão')
Metier.create(value: 'Comércio atacadista de resíduos de papel e papelão recicláveis')
Metier.create(value: 'Comércio atacadista de embalagens')
Metier.create(value: 'comércio atacadista de papel e papelão em bruto')
Metier.create(value: 'Comércio atacadista de outros produtos intermediários não-agropecuários não especific')
Metier.create(value: 'Comércio atacadista de máquinas aparelhos e equipamentos de uso agropecuário; suas pe')
Metier.create(value: 'Comércio atacadista de máquinas e equipamentos para o comércio; suas peças e acessório')
Metier.create(value: 'Comércio atacadista de máquinas e equipamentos para escritório')
Metier.create(value: 'Comércio atacadista de equipamentos de informática e comunicação')
Metier.create(value: 'Comércio atacadista de máquinas aparelhos e equipamentos de uso industrial')
Metier.create(value: 'Comércio atacadista de máquinas aparelhos e equipamentos odonto-médico-hospitalares e')
Metier.create(value: 'Comércio atacadista de bombas e compressores')
Metier.create(value: 'Comércio atacadista de máquinas aparelhos e equipamentos para outros usos não especif')
Metier.create(value: 'Comércio atacadista de mercadorias em geral sem predominância de artigos para uso na a')
Metier.create(value: 'Comércio atacadista de artigos para uso na agropecuária')
Metier.create(value: 'Comércio atacadista especializado em mercadorias não especificadas anteriormente')
Metier.create(value: 'Comércio varejista de mercadorias em geral com predominância de produtos alimentícios')
Metier.create(value: 'Comércio varejista de mercadorias em geral com predominância de produtos alimentícios')
Metier.create(value: 'Minimercados')
Metier.create(value: 'Mercearias e armazéns varejistas')
Metier.create(value: 'Comércio varejista de mercadorias em lojas de conveniência')
Metier.create(value: 'Lojas de departamentos ou magazines')
Metier.create(value: 'Lojas de variedades exclusive lojas de departamentos ou magazines')
Metier.create(value: 'Lojas duty free de aeroportos internacionais')
Metier.create(value: 'Comércio varejista de produtos de padaria e de confeitaria')
Metier.create(value: 'Comércio varejista de laticínios frios e conservas')
Metier.create(value: 'Comércio varejista de balas bombons e semelhantes')
Metier.create(value: 'Comércio varejista de carnes - açougues')
Metier.create(value: 'Comércio varejista de bebidas')
Metier.create(value: 'Tabacaria')
Metier.create(value: 'Comércio varejista de hortifrutigranjeiros')
Metier.create(value: 'Peixaria')
Metier.create(value: 'Comércio varejista de outros produtos alimentícios não especificados anteriormente')
Metier.create(value: 'Comércio varejista de tecidos')
Metier.create(value: 'Comércio varejista de artigos de armarinho')
Metier.create(value: 'Comércio varejista de artigos de cama mesa e banho')
Metier.create(value: 'Comércio varejista de artigos do vestuário e complementos')
Metier.create(value: 'Comércio varejista de calçados')
Metier.create(value: 'Comércio varejista de artigos de couro e de viagem')
Metier.create(value: 'Comércio varejista de produtos farmacêuticos alopáticos (farmácias e drogarias)')
Metier.create(value: 'Comércio varejista de produtos farmacêuticos homeopáticos')
Metier.create(value: 'Farmácias de manipulação')
Metier.create(value: 'Comércio varejista de artigos de perfumaria cosméticos e de higiene pessoal')
Metier.create(value: 'Comércio varejista de artigos médicos e ortopédicos')
Metier.create(value: 'Comércio varejista de medicamentos veterinários')
Metier.create(value: 'Comércio varejista de máquinas aparelhos e equipamentos elétrico eletrônico de uso d')
Metier.create(value: 'Comércio varejista de artigos fotográficos e cinematográficos')
Metier.create(value: 'Comércio varejista de instrumentos musicais e acessórios')
Metier.create(value: 'Comércio varejista de discos e fitas')
Metier.create(value: 'Comércio varejista de móveis')
Metier.create(value: 'Comércio varejista de artigos de colchoaria')
Metier.create(value: 'Comércio varejista de artigos de tapeçaria')
Metier.create(value: 'Comércio varejista de artigos de iluminação')
Metier.create(value: 'Comércio varejista de outros artigos de utilidade doméstica')
Metier.create(value: 'Comércio varejista de ferragens ferramentas e produtos metalúrgicos')
Metier.create(value: 'Comércio varejista de vidros espelhos vitrais e molduras')
Metier.create(value: 'Comércio varejista de material para pintura')
Metier.create(value: 'Comércio varejista de madeira e seus artefatos')
Metier.create(value: 'Comércio varejista de materiais elétricos para construção')
Metier.create(value: 'Comércio varejista de materiais hidráulicos')
Metier.create(value: 'Comércio varejista de materiais de construção em geral')
Metier.create(value: 'Comércio varejista de máquinas e equipamentos para escritório')
Metier.create(value: 'Comércio varejista de máquinas equipamentos e materiais de informática')
Metier.create(value: 'Comércio varejista de máquinas equipamentos e materiais de comunicação')
Metier.create(value: 'Comércio varejista de livros')
Metier.create(value: 'Comércio varejista de artigos de papelaria')
Metier.create(value: 'Comércio varejista de jornais e revistas')
Metier.create(value: 'Comércio varejista de gás liquefeito de petróleo (GLP)')
Metier.create(value: 'Comércio varejista de artigos de ótica')
Metier.create(value: 'Comércio varejista de artigos de relojoaria e joalheria')
Metier.create(value: 'Comércio varejista de artigos de souveniers  bijuterias e artesanatos')
Metier.create(value: 'Comércio varejista de bicicletas e triciclos; suas peças e acessórios')
Metier.create(value: 'Comércio varejista de artigos esportivos')
Metier.create(value: 'Comércio varejista de brinquedos e artigos recreativos')
Metier.create(value: 'Comércio varejista de plantas e flores naturais e artificiais e frutos ornamentais')
Metier.create(value: 'Comércio varejista de artigos de caça pesca e camping')
Metier.create(value: 'Comércio varejista de armas e munições')
Metier.create(value: 'Comércio varejista de objetos de arte')
Metier.create(value: 'Comércio varejista de artigos para animais ração e animais vivos para criação domésti')
Metier.create(value: 'Comércio varejista de peças e acessórios para eletrodomésticos e aparelhos eletrônicos')
Metier.create(value: 'Comércio varejista de fogos de artifício e artigos pirotécnicos')
Metier.create(value: 'Comércio varejista de embarcações e outros veículos recreativos; suas peças e acessóri')
Metier.create(value: 'Comércio varejista de outros produtos não especificados anteriormente')
Metier.create(value: 'Comércio varejista de antiguidades')
Metier.create(value: 'Comércio varejista de outros artigos usados em lojas')
Metier.create(value: 'Comércio varejista de artigos em geral por catálogo ou pedido pelo correio')
Metier.create(value: 'Comércio varejista de artigos em geral por televisão internet e outros meios de comu')
Metier.create(value: 'Comércio varejista realizado em vias públicas')
Metier.create(value: 'Comércio varejista a domicílio')
Metier.create(value: 'Comércio varejista realizado em postos móveis')
Metier.create(value: 'Comércio varejista realizado através de máquinas automáticas')
Metier.create(value: 'Outros tipos de comércio varejista não realizados em lojas')
Metier.create(value: 'Reparação e manutenção de máquinas e de aparelhos eletrodomésticos exclusive aparelho')
Metier.create(value: 'Reparação e manutenção de aparelhos telefônicos')
Metier.create(value: 'Reparação de calçados')
Metier.create(value: 'Chaveiros')
Metier.create(value: 'reparação de jóias e relógios')
Metier.create(value: 'Conserto e restauração de artigos de madeira e do mobiliário')
Metier.create(value: 'Reparação de bicicletas triciclos e outros veículos recreativos')
Metier.create(value: 'Reparação de outros objetos pessoais e domésticos')
Metier.create(value: 'Hotel com restaurante')
Metier.create(value: 'Apart-hotel (usado como hotel) com restaurante')
Metier.create(value: 'Motel (com serviço de alimentação)')
Metier.create(value: 'Hotel sem restaurante')
Metier.create(value: 'Apart-hotel (usado como hotel) sem restaurante')
Metier.create(value: 'Motel (sem serviço de alimentação)')
Metier.create(value: 'Albergues exclusive assistenciais')
Metier.create(value: 'Camping')
Metier.create(value: 'Pensão com serviço de alimentação')
Metier.create(value: 'Pensão sem serviço de alimentação')
Metier.create(value: 'Outros tipos de alojamento')
Metier.create(value: 'Restaurante')
Metier.create(value: 'Choperias whiskeria e outros estabelecimentos especializados em servir bebidas')
Metier.create(value: 'Lanchonete casas de chá de sucos e similares')
Metier.create(value: 'Cantina (serviço de alimentação privativo) - exploração própria')
Metier.create(value: 'Cantina (serviço de alimentação privativo) - exploração por terceiros')
Metier.create(value: 'Fornecimento de alimentos preparados preponderantemente para empresas')
Metier.create(value: 'Serviços de buffet')
Metier.create(value: 'Fornecimento de alimentos preparados preponderantemente para consumo domiciliar')
Metier.create(value: 'Outros serviços de alimentação (em traillers quiosques veículos e outros equipamento')
Metier.create(value: 'Transporte ferroviário de passageiros intermunicipal e interestadual')
Metier.create(value: 'Transporte ferroviário de cargas intermunicipal e interestadual')
Metier.create(value: 'Transporte ferroviário de passageiros municipal e intermunicipal metropolitano')
Metier.create(value: 'Transporte metroviário')
Metier.create(value: 'Transporte rodoviário de passageiros regular municipal urbano')
Metier.create(value: 'Transporte rodoviário de passageiros regular intermunicipal metropolitano')
Metier.create(value: 'Transporte rodoviário de passageiros regular municipal não urbano')
Metier.create(value: 'Transporte rodoviário de passageiros regular intermunicipal')
Metier.create(value: 'Transporte rodoviário de passageiros regular interestadual')
Metier.create(value: 'Transporte rodoviário de passageiros regular internacional')
Metier.create(value: 'Serviços de táxis')
Metier.create(value: 'Locação de veículos rodoviários de passageiros com motorista municipal')
Metier.create(value: 'Locação de veículos rodoviários de passageiros com motorista intermunicipal interest')
Metier.create(value: 'Organização de excursões em veículos rodoviários próprios municipal')
Metier.create(value: 'Organização de excursões em veículos rodoviários próprios intermunicipal interestadu')
Metier.create(value: 'Transporte escolar municipal')
Metier.create(value: 'Transporte escolar intermunicipal')
Metier.create(value: 'Transporte rodoviário de cargas em geral municipal')
Metier.create(value: 'Transporte rodoviário de cargas em geral intermunicipal interestadual e internaciona')
Metier.create(value: 'Locação de veículos rodoviários de carga com motorista')
Metier.create(value: 'Transporte rodoviário de produtos perigosos')
Metier.create(value: 'Transporte rodoviário de mudanças')
Metier.create(value: 'Serviço de guarda-móveis')
Metier.create(value: 'Transporte regular em bondes funiculares teleféricos ou trens próprios para exploraç')
Metier.create(value: 'Transporte dutoviário')
Metier.create(value: 'Transporte marítimo de cabotagem')
Metier.create(value: 'Transporte marítimo de longo curso')
Metier.create(value: 'Transporte por navegação interior de passageiros municipal não urbano')
Metier.create(value: 'Transporte por navegação interior de passageiros intermunicipal não urbano interesta')
Metier.create(value: 'Transporte por navegação interior de carga municipal não urbano')
Metier.create(value: 'Transporte por navegação interior de carga intermunicipal não urbano interestadual')
Metier.create(value: 'Transporte aquaviário municipal urbano')
Metier.create(value: 'Transporte aquaviário intermunicipal urbano')
Metier.create(value: 'Transporte aéreo regular')
Metier.create(value: 'Serviços de táxis aéreos e locação de aeronaves com tripulação')
Metier.create(value: 'Outros serviços de transporte aéreo não regular')
Metier.create(value: 'Transporte espacial')
Metier.create(value: 'Carga e descarga')
Metier.create(value: 'Armazéns gerais (emissão de warrants)')
Metier.create(value: 'Outros depósitos de mercadorias para terceiros')
Metier.create(value: 'Depósitos de mercadorias próprias')
Metier.create(value: 'Terminais rodoviários e ferroviários')
Metier.create(value: 'Operação de pontes túneis e rodovias')
Metier.create(value: 'Exploração de estacionamento para veículos')
Metier.create(value: 'Centrais de chamadas e reserva de táxis')
Metier.create(value: 'Outras atividades auxiliares aos transportes terrestres')
Metier.create(value: 'Operação de portos e terminais')
Metier.create(value: 'Rebocagem em estuários e portos')
Metier.create(value: 'Limpeza de cascos e manutenção de navios no porto')
Metier.create(value: 'Outras atividades auxiliares aos transportes aquaviários')
Metier.create(value: 'Operação de aeroportos e campos de aterrissagem')
Metier.create(value: 'Manutenção de aeronaves na pista')
Metier.create(value: 'Outras atividades auxiliares aos transportes aéreos')
Metier.create(value: 'Atividades de agências de viagens e organizadores de viagem')
Metier.create(value: 'Atividades de despachantes aduaneiros')
Metier.create(value: 'Atividades de comissaria')
Metier.create(value: 'Agenciamento de cargas')
Metier.create(value: 'Outras atividades relacionadas a organização do transporte de cargas')
Metier.create(value: 'Atividades do Correio Nacional')
Metier.create(value: 'Atividades do Correio Nacional executadas por franchising')
Metier.create(value: 'Serviços de malotes e entrega rápida não realizados pelo Correio Nacional')
Metier.create(value: 'Telecomunicações por fio')
Metier.create(value: 'Telecomunicações sem fio')
Metier.create(value: 'Telecomunicações por satélite')
Metier.create(value: 'Outras telecomunicações')
Metier.create(value: 'Provedores de acesso as redes de telecomunicações')
Metier.create(value: 'Banco Central')
Metier.create(value: 'Bancos comerciais')
Metier.create(value: 'Bancos múltiplos (com carteira comercial)')
Metier.create(value: 'Caixas econômicas')
Metier.create(value: 'Bancos cooperativos')
Metier.create(value: 'Cooperativas de crédito mútuo')
Metier.create(value: 'Cooperativas de crédito rural')
Metier.create(value: 'Bancos múltiplos (sem carteira comercial)')
Metier.create(value: 'Bancos de investimento')
Metier.create(value: 'Bancos de desenvolvimento')
Metier.create(value: 'Sociedades de crédito imobiliário')
Metier.create(value: 'Associações de poupança e empréstimo')
Metier.create(value: 'Companhias hipotecárias')
Metier.create(value: 'Sociedades de crédito financiamento e investimento')
Metier.create(value: 'Arrendamento mercantil')
Metier.create(value: 'Agências de desenvolvimento')
Metier.create(value: 'Administração de consórcios')
Metier.create(value: 'Administração de cartão de crédito')
Metier.create(value: 'Factoring')
Metier.create(value: 'Caixas de financiamento de corporações')
Metier.create(value: 'Securitização de créditos')
Metier.create(value: 'Sociedade de crédito ao microempreendedor')
Metier.create(value: 'Outras atividades de concessão de crédito')
Metier.create(value: 'Fundos mútuos de investimento')
Metier.create(value: 'Sociedades de capitalização')
Metier.create(value: 'Clubes de investimento')
Metier.create(value: 'Sociedades de investimento')
Metier.create(value: 'Sociedades de participação')
Metier.create(value: 'Escritórios de representação de bancos estrangeiros')
Metier.create(value: 'Holdings de instituições financeiras')
Metier.create(value: 'Licenciamento compra e venda e leasing de ativos intangíveis não financeiros exclusi')
Metier.create(value: 'Gestão de fundos para fins diversos exclusive investimentos')
Metier.create(value: 'Outras atividades de intermediação financeira não especificadas anteriormente')
Metier.create(value: 'Seguros de vida')
Metier.create(value: 'Seguro saúde')
Metier.create(value: 'Outros seguros não-vida')
Metier.create(value: 'Resseguros')
Metier.create(value: 'Previdência privada fechada')
Metier.create(value: 'Previdência privada aberta')
Metier.create(value: 'Planos de saúde')
Metier.create(value: 'Bolsa de valores')
Metier.create(value: 'Bolsa de mercadorias')
Metier.create(value: 'Bolsa de mercadorias e futuros')
Metier.create(value: 'Administração de mercados de balcão organizados')
Metier.create(value: 'Corretoras de títulos e valores mobiliários')
Metier.create(value: 'Distribuidoras de títulos e valores mobiliários')
Metier.create(value: 'Corretoras de câmbio')
Metier.create(value: 'Corretoras de contratos de mercadorias')
Metier.create(value: 'Administração de carteiras de títulos e valores para terceiros')
Metier.create(value: 'Serviços de liquidação e custódia')
Metier.create(value: 'Caixas de liquidação de mercados bursáteis')
Metier.create(value: 'Emissão de vales alimentação transporte e similares')
Metier.create(value: 'Outras atividades auxiliares da intermediação financeira não especificadas anteriormen')
Metier.create(value: 'Corretores e agentes de seguros e de planos de previdência privada e de saúde')
Metier.create(value: 'Peritos e avaliadores de seguros')
Metier.create(value: 'Auditoria e consultoria atuarial')
Metier.create(value: 'Clube de seguros')
Metier.create(value: 'Outras atividades auxiliares dos seguros e da previdência privada não especificadas a')
Metier.create(value: 'Incorporação e compra e venda de imóveis')
Metier.create(value: 'Aluguel de imóveis')
Metier.create(value: 'Corretagem e avaliação de imóveis')
Metier.create(value: 'Administração de imóveis por conta de terceiros')
Metier.create(value: 'Condomínio de prédios residenciais ou não')
Metier.create(value: 'Aluguel de automóveis sem motorista')
Metier.create(value: 'Aluguel de outros meios de transporte terrestre inclusive containers')
Metier.create(value: 'Aluguel de embarcações sem tripulação exclusive para fins recreativos')
Metier.create(value: 'Aluguel de aeronaves sem tripulação')
Metier.create(value: 'Aluguel de máquinas e equipamentos agrícolas')
Metier.create(value: 'Aluguel de máquinas e equipamentos para construção e engenharia civil inclusive andai')
Metier.create(value: 'Aluguel de máquinas e equipamentos para escritórios inclusive computadores e material')
Metier.create(value: 'Aluguel de aparelhos de jogos eletrônicos')
Metier.create(value: 'Aluguel de máquinas e equipamentos para extração de minérios e petróleo sem operador')
Metier.create(value: 'Aluguel de equipamentos científicos médicos e hospitalares sem operador')
Metier.create(value: 'Aluguel de outras máquinas e equipamentos comerciais industriais elétricos ou não s')
Metier.create(value: 'Aluguel de objetos de vestuário jóias calçados e outros acessórios')
Metier.create(value: 'Aluguel de móveis utensílios e aparelhos de uso doméstico e pessoal inclusive instru')
Metier.create(value: 'Aluguel de fitas vídeos discos cartuchos e similares')
Metier.create(value: 'Aluguel de material médico e paramédico')
Metier.create(value: 'Aluguel de material e equipamento esportivo')
Metier.create(value: 'Aluguel de outros objetos pessoais e domésticos')
Metier.create(value: 'Consultoria e/ou assessoria em sistemas de informática')
Metier.create(value: 'Desenvolvimento de programas de informática')
Metier.create(value: 'Processamento de dados')
Metier.create(value: 'Atividades de banco de dados')
Metier.create(value: 'Manutenção reparação e instalação de máquinas de escritório e de informática')
Metier.create(value: 'Outras atividades de informática não especificadas anteriormente')
Metier.create(value: 'Pesquisa e desenvolvimento das ciências físicas e naturais')
Metier.create(value: 'Pesquisa e desenvolvimento das ciências sociais e humanas')
Metier.create(value: 'Serviços advocatícios')
Metier.create(value: 'Atividades cartoriais')
Metier.create(value: 'Atividades auxiliares da justiça')
Metier.create(value: 'Atividades de contabilidade')
Metier.create(value: 'Atividades de auditoria contábil')
Metier.create(value: 'Pesquisas de mercado e de opinião pública')
Metier.create(value: 'Gestão de participações societárias (holdings)')
Metier.create(value: 'Sedes de empresas e unidades administrativas locais')
Metier.create(value: 'Assessoria as atividades agrícolas e pecuárias')
Metier.create(value: 'Atividades de assessoria em gestão empresarial')
Metier.create(value: 'Serviços técnicos de arquitetura')
Metier.create(value: 'Serviços técnicos de engenharia')
Metier.create(value: 'Serviços técnicos de cartografia topografia e geodésia')
Metier.create(value: 'Atividades de prospecção geológica')
Metier.create(value: 'Serviços de desenho técnico especializado')
Metier.create(value: 'Outros serviços técnicos especializados')
Metier.create(value: 'Ensaios de materiais e de produtos; análise de qualidade')
Metier.create(value: 'Agências de publicidade e propaganda')
Metier.create(value: 'Agenciamento e locação de espaços publicitários')
Metier.create(value: 'Outros serviços de publicidade')
Metier.create(value: 'Seleção e agenciamento de mão de obra')
Metier.create(value: 'Locação de mão de obra')
Metier.create(value: 'Atividades de investigação particular')
Metier.create(value: 'Atividades de vigilância e segurança privada')
Metier.create(value: 'Serviços de adestramento de cães de guarda')
Metier.create(value: 'Serviços de transporte de valores')
Metier.create(value: 'Atividades de limpeza em imóveis')
Metier.create(value: 'Serviços de dedetização desratização descupinização e similares')
Metier.create(value: 'Estúdios fotográficos')
Metier.create(value: 'Exploração de máquinas fotográficas de auto atendimento')
Metier.create(value: 'Laboratórios fotográficos')
Metier.create(value: 'Serviços de fotografias aéreas submarinas e similares')
Metier.create(value: 'Atividades de envasamento e empacotamento por conta de terceiros')
Metier.create(value: 'Serviços de tradução interpretação e similares')
Metier.create(value: 'Serviços de fotocópias e microfilmagem')
Metier.create(value: 'Serviços de contatos telefônicos')
Metier.create(value: 'Serviços de leiloeiros')
Metier.create(value: 'Serviços administrativos para terceiros')
Metier.create(value: 'Serviços de decoração de interiores')
Metier.create(value: 'Serviços de organização de eventos - exclusive culturais e desportivos')
Metier.create(value: 'Serviços de cobrança e de informações cadastrais')
Metier.create(value: 'Escafandria e mergulho')
Metier.create(value: 'Outros serviços prestados principalmente as empresas')
Metier.create(value: 'Administração pública em geral')
Metier.create(value: 'Regulação das atividades sociais e culturais')
Metier.create(value: 'Regulação das atividades econômicas')
Metier.create(value: 'Atividades de apoio . administração pública')
Metier.create(value: 'Relações exteriores')
Metier.create(value: 'Defesa')
Metier.create(value: 'Justiça')
Metier.create(value: 'Segurança pública')
Metier.create(value: 'Defesa civil')
Metier.create(value: 'Seguridade social')
Metier.create(value: 'Educação pré-escolar')
Metier.create(value: 'Educação fundamental')
Metier.create(value: 'Educação média de formação geral')
Metier.create(value: 'Educação média de formação técnica e profissional')
Metier.create(value: 'Educação Superior')
Metier.create(value: 'Ensino em autoescolas e cursos de pilotagem')
Metier.create(value: 'Educação supletiva')
Metier.create(value: 'Cursos de línguas estrangeiras')
Metier.create(value: 'Cursos de informática')
Metier.create(value: 'Cursos de aprendizagem e treinamento gerencial e profissional')
Metier.create(value: 'cursos ligados .s artes e cultura')
Metier.create(value: 'Outros cursos de educação continuada ou permanente')
Metier.create(value: 'Ensino . distância')
Metier.create(value: 'Educação especial')
Metier.create(value: 'Atividades de atendimento hospitalar')
Metier.create(value: 'Atividades de atendimento a urgências e emergências')
Metier.create(value: 'Atividades de clínica médica (clínicas consultórios e ambulatórios)')
Metier.create(value: 'Atividades de clínicas odontológicas (clínicas consultórios e ambulatórios)')
Metier.create(value: 'Serviços de vacinação e imunização humana')
Metier.create(value: 'Outras atividades de atenção ambulatorial')
Metier.create(value: 'Atividades dos laboratórios de anatomia patológica/citológica')
Metier.create(value: 'Atividades dos laboratórios de análises clínicas')
Metier.create(value: 'Serviços de diálise')
Metier.create(value: 'Serviços de raio-x radiodiagnóstico e radioterapia')
Metier.create(value: 'Serviços de quimioterapia')
Metier.create(value: 'Serviços de banco de sangue')
Metier.create(value: 'Outras atividades de serviços de complementação diagnóstica e terapêutica')
Metier.create(value: 'Serviços de enfermagem')
Metier.create(value: 'Serviços de nutrição')
Metier.create(value: 'Serviços de psicologia')
Metier.create(value: 'Serviços de fisioterapia e terapia ocupacional')
Metier.create(value: 'Serviços de fonoaudiologia')
Metier.create(value: 'Outras atividades de serviços profissionais da área de saúde')
Metier.create(value: 'Atividades de terapias alternativas')
Metier.create(value: 'Serviços de acupuntura')
Metier.create(value: 'Serviços de banco de leite materno')
Metier.create(value: 'Serviços de banco de esperma')
Metier.create(value: 'Serviços de banco de órgãos')
Metier.create(value: 'Serviços de remoções')
Metier.create(value: 'Outras atividades relacionadas com a atenção da saúde')
Metier.create(value: 'Serviços veterinários')
Metier.create(value: 'Asilos')
Metier.create(value: 'Orfanatos')
Metier.create(value: 'Albergues assistenciais')
Metier.create(value: 'Centros de reabilitação para dependentes químicos com alojamento')
Metier.create(value: 'Outros serviços sociais com alojamento')
Metier.create(value: 'Creches')
Metier.create(value: 'Centros de reabilitação para dependentes químicos sem alojamento')
Metier.create(value: 'Outros serviços sociais sem alojamento')
Metier.create(value: 'Limpeza urbana - exclusive gestão de aterros sanitários')
Metier.create(value: 'Gestão de aterros sanitários')
Metier.create(value: 'Gestão de redes de esgoto')
Metier.create(value: 'Outras atividades relacionadas a limpeza urbana e esgoto')
Metier.create(value: 'Atividades de organizações empresariais e patronais')
Metier.create(value: 'Atividades de organizações profissionais')
Metier.create(value: 'Atividades de organizações sindicais')
Metier.create(value: 'Atividades de organizações religiosas')
Metier.create(value: 'Atividades de organizações políticas')
Metier.create(value: 'Outras atividades associativas não especificadas anteriormente')
Metier.create(value: 'Estúdios cinematográficos')
Metier.create(value: 'Atividades de produção de filmes e fitas de vídeo exclusive estúdios fotográficos')
Metier.create(value: 'Serviços de dublagem e mixagem sonora')
Metier.create(value: 'Outras atividades relacionadas a produção de filmes e fitas de vídeos')
Metier.create(value: 'Distribuição de filmes e de vídeo')
Metier.create(value: 'Projeção de filmes e de vídeos')
Metier.create(value: 'Atividades de rádio')
Metier.create(value: 'Atividades de televisão aberta')
Metier.create(value: 'Atividades de televisão por assinatura')
Metier.create(value: 'Companhias de teatro')
Metier.create(value: 'Outras companhias artísticas exclusive de teatro')
Metier.create(value: 'Produção organização e promoção de espetáculos artísticos e eventos culturais')
Metier.create(value: 'Restauração de obras de arte')
Metier.create(value: 'Gestão de direitos autorais de obras artísticas literárias e musicais')
Metier.create(value: 'Outros serviços especializados ligados as atividades artísticas')
Metier.create(value: 'Exploração de salas de espetáculos')
Metier.create(value: 'Agências de venda de ingressos para salas de espetáculos')
Metier.create(value: 'Estúdios de gravação de som')
Metier.create(value: 'Serviços de sonorização e outras atividades ligadas . gestão de salas de espetáculos')
Metier.create(value: 'Produção de espetáculos circenses marionetes e similares')
Metier.create(value: 'Produção de espetáculos de rodeios vaquejadas e similares')
Metier.create(value: 'Academias de dança')
Metier.create(value: 'Discotecas danceterias e similares')
Metier.create(value: 'Outras atividades de espetáculos não especificadas anteriormente')
Metier.create(value: 'Atividades de agências de notícias')
Metier.create(value: 'Atividades de bibliotecas e arquivos')
Metier.create(value: 'Gestão de museus')
Metier.create(value: 'Conservação de lugares e edifícios históricos')
Metier.create(value: 'Atividades de jardins botânicos zoológicos parques nacionais e reservas ecológicas')
Metier.create(value: 'Clubes sociais desportivos e similares')
Metier.create(value: 'Organização e exploração de atividades desportivas')
Metier.create(value: 'Gestão de instalações desportivas')
Metier.create(value: 'Ensino de esportes')
Metier.create(value: 'Academias de ginástica')
Metier.create(value: 'Atividades ligadas . corrida de cavalos')
Metier.create(value: 'Outras atividades desportivas')
Metier.create(value: 'Exploração de bingos')
Metier.create(value: 'Atividades das concessionárias e da venda de bilhetes de loterias')
Metier.create(value: 'Atividades de sorteio via telefone')
Metier.create(value: 'Exploração de outros jogos de azar')
Metier.create(value: 'Exploração de boliches')
Metier.create(value: 'Exploração de fliperamas e jogos eletrônicos')
Metier.create(value: 'Exploração de parques de diversões e similares')
Metier.create(value: 'Exploração de jogos de sinuca bilhar e similares')
Metier.create(value: 'Outras atividades relacionadas ao lazer')
Metier.create(value: 'Lavanderias e tinturarias')
Metier.create(value: 'Toalheiros')
Metier.create(value: 'Cabeleireiros')
Metier.create(value: 'Manicures e outros serviços de tratamento de beleza')
Metier.create(value: 'Gestão e manutenção de cemitérios')
Metier.create(value: 'Serviços de cremação de cadáveres humanos e animais')
Metier.create(value: 'Serviços de sepultamento')
Metier.create(value: 'Serviços de funerárias')
Metier.create(value: 'Outras atividades funerárias')
Metier.create(value: 'Atividades de manutenção do físico corporal')
Metier.create(value: 'Atividades de agências matrimoniais')
Metier.create(value: 'Atividades de embelezamento de animais')
Metier.create(value: 'Outras atividades de serviços pessoais não especificadas anteriormente')
Metier.create(value: 'Serviços domésticos')
Metier.create(value: 'Organismos internacionais e outras instituições extraterritoriais')

Occupation.create(value: 'Dentista')
Occupation.create(value: 'Médico(a)')
Occupation.create(value: 'Militar do Exército/Marinha/Aeronáutica')
Occupation.create(value: 'Professor(a) (ensino básico, ensino fundamental, médio ou superior)')
Occupation.create(value: 'Professor(a) Educação Física ou Personal Trainer')
Occupation.create(value: 'Servidor Público/Funcionário Público')
Occupation.create(value: 'Engenheiro(a)/Arquiteto(a)')
Occupation.create(value: 'Funcionário do Grupo Itaú')
Occupation.create(value: 'Estudante')
Occupation.create(value: 'Proprietário de Empresas/Negócios')
Occupation.create(value: 'Venda/Representante Comercial')
Occupation.create(value: 'Aposentado')
Occupation.create(value: 'Não trabalha')
Occupation.create(value: 'Outros')
Occupation.create(value: 'Não Informado')

Person.create(name: 'Bornia & Dianin Administradora de Negócios, Serviços e Corretora de Seguros', person_type_id: 2, metier_id: 943, contact: 'Paulo César Dianin')
Person.create(name: 'Paulo César Dianin Junior', person_type_id: 1, birth: '08/16/1982', marital_status_id: 2, gender_id: 2, occupation_id: 14, salary_range_id: 4)
Person.create(name: 'Paulo César Dianin', person_type_id: 1, birth: '19/10/1962', marital_status_id: 2, gender_id: 2, occupation_id: 14, salary_range_id: 3)

DocumentType.create(value: 'CPF')
DocumentType.create(value: 'CNH')
DocumentType.create(value: 'CNPJ')
DocumentType.create(value: 'RG')
DocumentType.create(value: 'RNE')

Productive.create(name: 'Paulo César Dianin', short_name: 'Paulo', gender_id: 1, cpf: '43646107987', email: 'paulo@bdseguros.com.br', birth: '19/10/1962', status: true)
Productive.create(name: 'Paulo César Dianin Junior', short_name: 'Junior', gender_id: 1, cpf: '04039552970', email: 'maxjuniorbr@gmail.com', birth: '08/06/1982', status: true)